apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    heritage: Tiller
    release: cityeyes
  name: cityeyes-postgresql-expose
  namespace: default
spec:
  ports:
  - name: postgresql
    nodePort: 32006
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: cityeyes
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    heritage: Tiller
    release: paas
  name: paas-postgresql-expose
  namespace: default
spec:
  ports:
  - name: postgresql
    nodePort: 32005
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: paas
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: acldb
  name: acldb-expose
  namespace: default
spec:
  ports:
  - nodePort: 32004
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: acldb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

