apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-acl
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-acl
  hostPath:
    path: "/mysqlBackup_acl"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-acl
spec: 
  storageClassName: class-acl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
