apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cityeyes
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-cityeyes
  hostPath:
    path: "/pgBackup_cityeyes"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cityeyes
spec: 
  storageClassName: class-cityeyes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
