apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-map
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-map
  hostPath:
    path: "/mapBackup"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-map
spec: 
  storageClassName: class-map
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
