apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-maven
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-maven
  hostPath:
    path: "/mavenRepo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-maven
spec: 
  storageClassName: class-maven
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi