apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-media
  hostPath:
    path: "/deeplook_media"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
spec: 
  storageClassName: class-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi