apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs
  nfs:
    server: 10.100.95.27
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs
  resources:
    requests:
      storage: 100Gi