apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-maven
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs-maven
  nfs:
    server: 10.100.55.66
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-maven
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs-maven
  resources:
    requests:
      storage: 100Gi
