apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-war
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs-war
  nfs:
    server: 10.100.87.87
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-war
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: class-nfs-war
  resources:
    requests:
      storage: 100Gi
