apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paas
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-paas
  hostPath:
    path: "/pgBackup_paas"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-paas
spec: 
  storageClassName: class-paas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
