apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-registry
  hostPath:
    path: "/registryBackup"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-registry
spec: 
  storageClassName: class-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
