apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-war
spec:   
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: class-war
  hostPath:
    path: "/warDeeplook"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-war
spec: 
  storageClassName: class-war
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi