apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  labels:
    app: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
     labels:
       app: registry-ui
    spec:
      containers:
      - image: konradkleine/docker-registry-frontend:v2
        name: registry-ui
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: 'registry'
        - name: ENV_DOCKER_REGISTRY_PORT
          value: '5000'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  labels:
    app: registry-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31116
  selector:
    app: registry-ui