apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-maven-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-maven-server
  template:
    metadata:
      labels:
        role: nfs-maven-server
    spec:
      nodeSelector:
        machine: storage
      containers:
      - name: nfs-maven-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mymaven
      volumes:
        - name: mymaven
          persistentVolumeClaim:
            claimName: pvc-maven
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-maven-server
spec:
  clusterIP: 10.100.55.66
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-maven-server
