apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-war-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-war-server
  template:
    metadata:
      labels:
        role: nfs-war-server
    spec:
      nodeSelector:
        machine: storage
      containers:
      - name: nfs-war-server
        image: 140.96.29.86:31115/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mywar
      volumes:
        - name: mywar
          persistentVolumeClaim:
            claimName: pvc-war
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-war-server
spec:
  clusterIP: 10.100.87.87
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-war-server
