apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
    chart: rabbitmq-1.1.9
    heritage: Tiller
    release: mq
  name: mq-rabbitmq-expose
  namespace: default
spec:
  ports:
  - name: stats
    nodePort: 32007
    port: 5672
    protocol: TCP
    targetPort: stats
  selector:
    app: rabbitmq
    release: mq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
