apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas
  labels:
    app: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas
  template:
    metadata:
     labels:
       app: paas
    spec:
      containers:
      - name: paas
        image: tomcat:7-jre8-alpine
        env:
        - name: CATALINA_OPTS
          value: "-Duser.timezone=Asia/Taipei"
        volumeMounts:
        - name: samba-webapps
          mountPath: /usr/local/tomcat/webapps
        ports:
        - containerPort: 8080
      volumes:
      - name: samba-webapps
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes/webapps/paas"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
---
apiVersion: v1
kind: Service
metadata:
  name: paas
  labels:
    app: paas
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: paas