apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas
  labels:
    app: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas
  template:
    metadata:
     labels:
       app: paas
    spec:
      nodeSelector:
        machine: storage
      initContainers:
      - name: gitclone
        image: alpine/git
        command: ["sh","-c","rm -rf /git/* && git clone --single-branch -b develop https://2e990ac7f19037aca1b3672ee443f597a23e2995@github.com/ITRI-ICL-DivX/deeplook_paas.git && sleep 2"]
        volumeMounts:
        - name: git-repo
          mountPath: /git
      containers:
      - name: build-war
        image: maven:3.5.4-jdk-8-alpine
        command: ["sh","-c"]
        args:
          - cd /usr/src/mymaven/deeplook_paas;
            sh /usr/src/mymaven/deeplook_paas/settingScript --mq_host mq-rabbitmq --solr_url deeplook --db_host paas-postgresql --db_name postgres --db_url paas-postgresql:5432/postgres;
            mvn clean package -nsu -Dmaven.test.skip=true;
            cp /usr/src/mymaven/deeplook_paas/target/PaaS.war /target;
            while :; do sleep 2073600; done;
        volumeMounts:
        - name: samba-maven-repo
          mountPath: /root/.m2
        - name: git-repo
          mountPath: /usr/src/mymaven
        - name: after-build
          mountPath: /target
      - name: paas
        image: tomcat:7-jre8-alpine
        env:
        - name: CATALINA_OPTS
          value: "-Duser.timezone=Asia/Taipei"
        volumeMounts:
        - name: after-build
          mountPath: /usr/local/tomcat/webapps
        - name: git-repo
          mountPath: /repo
        ports:
        - containerPort: 8080
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: after-build
        emptyDir: {}
      - name: samba-maven-repo
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes/mavenRepo"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
---
apiVersion: v1
kind: Service
metadata:
  name: paas
  labels:
    app: paas
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: paas
