apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas
  labels:
    app: paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas
  template:
    metadata:
     labels:
       app: paas
    spec:
      nodeSelector:
        machine: storage
      containers:
      - name: paas
        image: aquamars00/deeplook_paas:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paas
  labels:
    app: paas
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: paas