apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeplook
  labels:
    app: deeplook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeplook
  template:
    metadata:
     labels:
       app: deeplook
    spec:
      nodeSelector:
        machine: storage
      containers:
      - name: deeplook
        image: tomcat:8-jre8
        env:
        - name: CATALINA_OPTS
          value: "-Duser.timezone=Asia/Taipei"
        volumeMounts:
        - name: samba-webapps
          mountPath: /usr/local/tomcat/webapps
        - name: samba-root
          mountPath: /var/www/html/
        ports:
        - containerPort: 8080
      volumes:
      - name: samba-webapps
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes/webapps/deeplook"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
      - name: samba-root
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes/"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
---
apiVersion: v1
kind: Service
metadata:
  name: deeplook
  labels:
    app: deeplook
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32010
  selector:
    app: deeplook
