apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
     labels:
       app: registry
    spec:
      nodeSelector:
        machine: storage
      containers:
      - name: registry
        image: registry:2.6.2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-local
          mountPath: /var/lib/registry
      volumes:
      - name: registry-local
        persistentVolumeClaim:
          claimName: pvc-registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31115
  selector:
    app: registry