apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-classify
  labels:
    app: engine-classify
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: engine-classify
  template:
    metadata:
     labels:
       app: engine-classify
    spec:
      nodeSelector:
        machine: gpu
        gpu: 1080ti
      containers:
      - name: engine-classify
        image: aquamars00/deeplook_engine_classify:1.2
        command: ["/bin/bash","-c"]
        args:
          - /etc/init.d/atd start;
            cd /root;
            echo 'java -jar /root/Orchestrator-0.2.7.jar &' | at now;
            sleep 1234567;
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: media-root
          mountPath: /var/www/html/
        - name: config
          mountPath: /root/config.properties
          subPath: config.properties
        - name: varlog
          mountPath: /root/log
      - name: engine-classify-agent
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/*.log']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      - name: media-root
        persistentVolumeClaim:
          claimName: pvc-media
      - name: config
        configMap:
          name: engine-classify