apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-classify
  labels:
    app: engine-classify
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: engine-classify
  template:
    metadata:
     labels:
       app: engine-classify
    spec:
      nodeSelector:
        machine: gpu
        gpu: 1080ti
      containers:
      - name: engine-classify
        image: 140.96.29.86:31115/classify:1.2
        command: ["/bin/bash","-c"]
        args:
          - ln -s -f /root/tmp_config/config.properties /root/config.properties;
            /etc/init.d/atd start;
            cd /root;
            echo 'java -jar /root/Orchestrator-0.2.7.jar &' | at now;
            sleep 1234567;
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: samba
          mountPath: /var/www/html/
        - name: config
          mountPath: /root/tmp_config
        - name: varlog
          mountPath: /root/log
      - name: engine-classify-agent
        image: busybox
        args: [/bin/sh, -c, 'tail -n0 -F /var/log/*']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      - name: samba
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
      - name: config
        configMap:
          name: engine-classify