apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-classify
  labels:
    app: engine-classify
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: engine-classify
  template:
    metadata:
     labels:
       app: engine-classify
    spec:
      containers:
      - name: engine-classify
        image: 140.96.29.86:31115/classify:1.2
        command: ["/bin/bash","-c"]
        args:
          - cp /root/tmp_config/config.properties /root/config.properties;
            /etc/init.d/atd start;
            sleep 1234567;
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: samba
          mountPath: /var/www/html/
        - name: config
          mountPath: /root/tmp_config
      volumes:
      - name: samba
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//140.96.29.33/snakeeyes"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
      - name: config
        configMap:
          name: engine-classify
#          items:
#          - key: config.properties
#            path: config.properties
---
apiVersion: v1
kind: Service
metadata:
  name: engine-classify
  labels:
    app: engine-classify
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: engine-classify
